// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package yak_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	// 注册用户
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...client.CallOption) (*RegisterUserResponse, error)
	// 用户登录
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...client.CallOption) (*LoginUserResponse, error)
	// 密码重置
	ResetUser(ctx context.Context, in *ResetUserRequest, opts ...client.CallOption) (*ResetUserResponse, error)
	// 修改用户信息
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...client.CallOption) (*UpdateUserProfileResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "yak.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...client.CallOption) (*RegisterUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.RegisterUser", in)
	out := new(RegisterUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...client.CallOption) (*LoginUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginUser", in)
	out := new(LoginUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ResetUser(ctx context.Context, in *ResetUserRequest, opts ...client.CallOption) (*ResetUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.ResetUser", in)
	out := new(ResetUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...client.CallOption) (*UpdateUserProfileResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUserProfile", in)
	out := new(UpdateUserProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 注册用户
	RegisterUser(context.Context, *RegisterUserRequest, *RegisterUserResponse) error
	// 用户登录
	LoginUser(context.Context, *LoginUserRequest, *LoginUserResponse) error
	// 密码重置
	ResetUser(context.Context, *ResetUserRequest, *ResetUserResponse) error
	// 修改用户信息
	UpdateUserProfile(context.Context, *UpdateUserProfileRequest, *UpdateUserProfileResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		RegisterUser(ctx context.Context, in *RegisterUserRequest, out *RegisterUserResponse) error
		LoginUser(ctx context.Context, in *LoginUserRequest, out *LoginUserResponse) error
		ResetUser(ctx context.Context, in *ResetUserRequest, out *ResetUserResponse) error
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, out *UpdateUserProfileResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) RegisterUser(ctx context.Context, in *RegisterUserRequest, out *RegisterUserResponse) error {
	return h.UserServiceHandler.RegisterUser(ctx, in, out)
}

func (h *userServiceHandler) LoginUser(ctx context.Context, in *LoginUserRequest, out *LoginUserResponse) error {
	return h.UserServiceHandler.LoginUser(ctx, in, out)
}

func (h *userServiceHandler) ResetUser(ctx context.Context, in *ResetUserRequest, out *ResetUserResponse) error {
	return h.UserServiceHandler.ResetUser(ctx, in, out)
}

func (h *userServiceHandler) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, out *UpdateUserProfileResponse) error {
	return h.UserServiceHandler.UpdateUserProfile(ctx, in, out)
}
