// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

package yak_permissions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Menu struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Router               string   `protobuf:"bytes,5,opt,name=router,proto3" json:"router,omitempty"`
	Hidden               int64    `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	ParentId             string   `protobuf:"bytes,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ParentPath           string   `protobuf:"bytes,8,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	Creator              string   `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *Menu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Menu) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Menu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Menu) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *Menu) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *Menu) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Menu) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

func (m *Menu) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type CreateMenuRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Router               string   `protobuf:"bytes,5,opt,name=router,proto3" json:"router,omitempty"`
	Hidden               int64    `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	ParentId             string   `protobuf:"bytes,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ParentPath           string   `protobuf:"bytes,8,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	Creator              string   `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMenuRequest) Reset()         { *m = CreateMenuRequest{} }
func (m *CreateMenuRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMenuRequest) ProtoMessage()    {}
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{1}
}

func (m *CreateMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMenuRequest.Unmarshal(m, b)
}
func (m *CreateMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMenuRequest.Marshal(b, m, deterministic)
}
func (m *CreateMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMenuRequest.Merge(m, src)
}
func (m *CreateMenuRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMenuRequest.Size(m)
}
func (m *CreateMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMenuRequest proto.InternalMessageInfo

func (m *CreateMenuRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *CreateMenuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMenuRequest) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CreateMenuRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *CreateMenuRequest) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *CreateMenuRequest) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *CreateMenuRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *CreateMenuRequest) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

func (m *CreateMenuRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type CreateMenuResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMenuResponse) Reset()         { *m = CreateMenuResponse{} }
func (m *CreateMenuResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMenuResponse) ProtoMessage()    {}
func (*CreateMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{2}
}

func (m *CreateMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMenuResponse.Unmarshal(m, b)
}
func (m *CreateMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMenuResponse.Marshal(b, m, deterministic)
}
func (m *CreateMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMenuResponse.Merge(m, src)
}
func (m *CreateMenuResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMenuResponse.Size(m)
}
func (m *CreateMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMenuResponse proto.InternalMessageInfo

type DeleteMenuRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMenuRequest) Reset()         { *m = DeleteMenuRequest{} }
func (m *DeleteMenuRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMenuRequest) ProtoMessage()    {}
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{3}
}

func (m *DeleteMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMenuRequest.Unmarshal(m, b)
}
func (m *DeleteMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMenuRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMenuRequest.Merge(m, src)
}
func (m *DeleteMenuRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMenuRequest.Size(m)
}
func (m *DeleteMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMenuRequest proto.InternalMessageInfo

func (m *DeleteMenuRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

type DeleteMenuResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMenuResponse) Reset()         { *m = DeleteMenuResponse{} }
func (m *DeleteMenuResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMenuResponse) ProtoMessage()    {}
func (*DeleteMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{4}
}

func (m *DeleteMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMenuResponse.Unmarshal(m, b)
}
func (m *DeleteMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMenuResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMenuResponse.Merge(m, src)
}
func (m *DeleteMenuResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMenuResponse.Size(m)
}
func (m *DeleteMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMenuResponse proto.InternalMessageInfo

type UpdateMenuRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Router               string   `protobuf:"bytes,5,opt,name=router,proto3" json:"router,omitempty"`
	Hidden               int64    `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	ParentId             string   `protobuf:"bytes,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ParentPath           string   `protobuf:"bytes,8,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	Creator              string   `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMenuRequest) Reset()         { *m = UpdateMenuRequest{} }
func (m *UpdateMenuRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuRequest) ProtoMessage()    {}
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{5}
}

func (m *UpdateMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuRequest.Unmarshal(m, b)
}
func (m *UpdateMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuRequest.Merge(m, src)
}
func (m *UpdateMenuRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuRequest.Size(m)
}
func (m *UpdateMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuRequest proto.InternalMessageInfo

func (m *UpdateMenuRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *UpdateMenuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateMenuRequest) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *UpdateMenuRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *UpdateMenuRequest) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *UpdateMenuRequest) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *UpdateMenuRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *UpdateMenuRequest) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

func (m *UpdateMenuRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type UpdateMenuResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMenuResponse) Reset()         { *m = UpdateMenuResponse{} }
func (m *UpdateMenuResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuResponse) ProtoMessage()    {}
func (*UpdateMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{6}
}

func (m *UpdateMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuResponse.Unmarshal(m, b)
}
func (m *UpdateMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuResponse.Merge(m, src)
}
func (m *UpdateMenuResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuResponse.Size(m)
}
func (m *UpdateMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuResponse proto.InternalMessageInfo

type QueryMenuRequest struct {
	Params               []byte   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMenuRequest) Reset()         { *m = QueryMenuRequest{} }
func (m *QueryMenuRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMenuRequest) ProtoMessage()    {}
func (*QueryMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{7}
}

func (m *QueryMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMenuRequest.Unmarshal(m, b)
}
func (m *QueryMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMenuRequest.Marshal(b, m, deterministic)
}
func (m *QueryMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMenuRequest.Merge(m, src)
}
func (m *QueryMenuRequest) XXX_Size() int {
	return xxx_messageInfo_QueryMenuRequest.Size(m)
}
func (m *QueryMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMenuRequest proto.InternalMessageInfo

func (m *QueryMenuRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryMenuResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Menus                []*Menu  `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMenuResponse) Reset()         { *m = QueryMenuResponse{} }
func (m *QueryMenuResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMenuResponse) ProtoMessage()    {}
func (*QueryMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{8}
}

func (m *QueryMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMenuResponse.Unmarshal(m, b)
}
func (m *QueryMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMenuResponse.Marshal(b, m, deterministic)
}
func (m *QueryMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMenuResponse.Merge(m, src)
}
func (m *QueryMenuResponse) XXX_Size() int {
	return xxx_messageInfo_QueryMenuResponse.Size(m)
}
func (m *QueryMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMenuResponse proto.InternalMessageInfo

func (m *QueryMenuResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryMenuResponse) GetMenus() []*Menu {
	if m != nil {
		return m.Menus
	}
	return nil
}

type GetMenuRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMenuRequest) Reset()         { *m = GetMenuRequest{} }
func (m *GetMenuRequest) String() string { return proto.CompactTextString(m) }
func (*GetMenuRequest) ProtoMessage()    {}
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{9}
}

func (m *GetMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMenuRequest.Unmarshal(m, b)
}
func (m *GetMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMenuRequest.Marshal(b, m, deterministic)
}
func (m *GetMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMenuRequest.Merge(m, src)
}
func (m *GetMenuRequest) XXX_Size() int {
	return xxx_messageInfo_GetMenuRequest.Size(m)
}
func (m *GetMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMenuRequest proto.InternalMessageInfo

func (m *GetMenuRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

type GetMenuResponse struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Router               string   `protobuf:"bytes,5,opt,name=router,proto3" json:"router,omitempty"`
	Hidden               int64    `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	ParentId             string   `protobuf:"bytes,7,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ParentPath           string   `protobuf:"bytes,8,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	Creator              string   `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMenuResponse) Reset()         { *m = GetMenuResponse{} }
func (m *GetMenuResponse) String() string { return proto.CompactTextString(m) }
func (*GetMenuResponse) ProtoMessage()    {}
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{10}
}

func (m *GetMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMenuResponse.Unmarshal(m, b)
}
func (m *GetMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMenuResponse.Marshal(b, m, deterministic)
}
func (m *GetMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMenuResponse.Merge(m, src)
}
func (m *GetMenuResponse) XXX_Size() int {
	return xxx_messageInfo_GetMenuResponse.Size(m)
}
func (m *GetMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMenuResponse proto.InternalMessageInfo

func (m *GetMenuResponse) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *GetMenuResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetMenuResponse) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *GetMenuResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *GetMenuResponse) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *GetMenuResponse) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *GetMenuResponse) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *GetMenuResponse) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

func (m *GetMenuResponse) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type CreateRoleRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{11}
}

func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(m, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleRequest) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CreateRoleRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *CreateRoleRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type CreateRoleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleResponse) Reset()         { *m = CreateRoleResponse{} }
func (m *CreateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoleResponse) ProtoMessage()    {}
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{12}
}

func (m *CreateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleResponse.Unmarshal(m, b)
}
func (m *CreateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleResponse.Merge(m, src)
}
func (m *CreateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoleResponse.Size(m)
}
func (m *CreateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleResponse proto.InternalMessageInfo

type DeleteRoleRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleRequest) Reset()         { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()    {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{13}
}

func (m *DeleteRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleRequest.Unmarshal(m, b)
}
func (m *DeleteRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleRequest.Merge(m, src)
}
func (m *DeleteRoleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleRequest.Size(m)
}
func (m *DeleteRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleRequest proto.InternalMessageInfo

func (m *DeleteRoleRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

type DeleteRoleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleResponse) Reset()         { *m = DeleteRoleResponse{} }
func (m *DeleteRoleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleResponse) ProtoMessage()    {}
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{14}
}

func (m *DeleteRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleResponse.Unmarshal(m, b)
}
func (m *DeleteRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleResponse.Merge(m, src)
}
func (m *DeleteRoleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleResponse.Size(m)
}
func (m *DeleteRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleResponse proto.InternalMessageInfo

type UpdateRoleRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{15}
}

func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(m, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *UpdateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRoleRequest) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *UpdateRoleRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *UpdateRoleRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type UpdateRoleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleResponse) Reset()         { *m = UpdateRoleResponse{} }
func (m *UpdateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleResponse) ProtoMessage()    {}
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{16}
}

func (m *UpdateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleResponse.Unmarshal(m, b)
}
func (m *UpdateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleResponse.Merge(m, src)
}
func (m *UpdateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleResponse.Size(m)
}
func (m *UpdateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleResponse proto.InternalMessageInfo

type QueryRoleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRoleRequest) Reset()         { *m = QueryRoleRequest{} }
func (m *QueryRoleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRoleRequest) ProtoMessage()    {}
func (*QueryRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{17}
}

func (m *QueryRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoleRequest.Unmarshal(m, b)
}
func (m *QueryRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoleRequest.Marshal(b, m, deterministic)
}
func (m *QueryRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoleRequest.Merge(m, src)
}
func (m *QueryRoleRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRoleRequest.Size(m)
}
func (m *QueryRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoleRequest proto.InternalMessageInfo

type QueryRoleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRoleResponse) Reset()         { *m = QueryRoleResponse{} }
func (m *QueryRoleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRoleResponse) ProtoMessage()    {}
func (*QueryRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{18}
}

func (m *QueryRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoleResponse.Unmarshal(m, b)
}
func (m *QueryRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoleResponse.Marshal(b, m, deterministic)
}
func (m *QueryRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoleResponse.Merge(m, src)
}
func (m *QueryRoleResponse) XXX_Size() int {
	return xxx_messageInfo_QueryRoleResponse.Size(m)
}
func (m *QueryRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoleResponse proto.InternalMessageInfo

type GetRoleRequest struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleRequest) Reset()         { *m = GetRoleRequest{} }
func (m *GetRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleRequest) ProtoMessage()    {}
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{19}
}

func (m *GetRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleRequest.Unmarshal(m, b)
}
func (m *GetRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleRequest.Merge(m, src)
}
func (m *GetRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleRequest.Size(m)
}
func (m *GetRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleRequest proto.InternalMessageInfo

func (m *GetRoleRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *GetRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRoleResponse struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sequence             int64    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleResponse) Reset()         { *m = GetRoleResponse{} }
func (m *GetRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoleResponse) ProtoMessage()    {}
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{20}
}

func (m *GetRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleResponse.Unmarshal(m, b)
}
func (m *GetRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleResponse.Marshal(b, m, deterministic)
}
func (m *GetRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleResponse.Merge(m, src)
}
func (m *GetRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoleResponse.Size(m)
}
func (m *GetRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleResponse proto.InternalMessageInfo

func (m *GetRoleResponse) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *GetRoleResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetRoleResponse) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *GetRoleResponse) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetRoleResponse) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Menu)(nil), "yak.permissions.Menu")
	proto.RegisterType((*CreateMenuRequest)(nil), "yak.permissions.CreateMenuRequest")
	proto.RegisterType((*CreateMenuResponse)(nil), "yak.permissions.CreateMenuResponse")
	proto.RegisterType((*DeleteMenuRequest)(nil), "yak.permissions.DeleteMenuRequest")
	proto.RegisterType((*DeleteMenuResponse)(nil), "yak.permissions.DeleteMenuResponse")
	proto.RegisterType((*UpdateMenuRequest)(nil), "yak.permissions.UpdateMenuRequest")
	proto.RegisterType((*UpdateMenuResponse)(nil), "yak.permissions.UpdateMenuResponse")
	proto.RegisterType((*QueryMenuRequest)(nil), "yak.permissions.QueryMenuRequest")
	proto.RegisterType((*QueryMenuResponse)(nil), "yak.permissions.QueryMenuResponse")
	proto.RegisterType((*GetMenuRequest)(nil), "yak.permissions.GetMenuRequest")
	proto.RegisterType((*GetMenuResponse)(nil), "yak.permissions.GetMenuResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "yak.permissions.CreateRoleRequest")
	proto.RegisterType((*CreateRoleResponse)(nil), "yak.permissions.CreateRoleResponse")
	proto.RegisterType((*DeleteRoleRequest)(nil), "yak.permissions.DeleteRoleRequest")
	proto.RegisterType((*DeleteRoleResponse)(nil), "yak.permissions.DeleteRoleResponse")
	proto.RegisterType((*UpdateRoleRequest)(nil), "yak.permissions.UpdateRoleRequest")
	proto.RegisterType((*UpdateRoleResponse)(nil), "yak.permissions.UpdateRoleResponse")
	proto.RegisterType((*QueryRoleRequest)(nil), "yak.permissions.QueryRoleRequest")
	proto.RegisterType((*QueryRoleResponse)(nil), "yak.permissions.QueryRoleResponse")
	proto.RegisterType((*GetRoleRequest)(nil), "yak.permissions.GetRoleRequest")
	proto.RegisterType((*GetRoleResponse)(nil), "yak.permissions.GetRoleResponse")
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_c837ef01cbda0ad8) }

var fileDescriptor_c837ef01cbda0ad8 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x96, 0x4b, 0x6f, 0xd4, 0x30,
	0x10, 0xc7, 0x9b, 0xee, 0xab, 0x3b, 0x20, 0xda, 0x35, 0x0f, 0x59, 0x7b, 0x80, 0xc5, 0x5c, 0x56,
	0x54, 0xda, 0x43, 0xb9, 0x72, 0x03, 0x09, 0x71, 0x00, 0x95, 0x50, 0xc4, 0x39, 0x24, 0x23, 0x35,
	0xa2, 0xb1, 0x83, 0x9d, 0x20, 0xf5, 0x13, 0xa0, 0x7e, 0x53, 0xee, 0xa8, 0x77, 0x64, 0xc7, 0x9b,
	0x78, 0x93, 0x78, 0xb5, 0x42, 0x42, 0xa0, 0xf6, 0x36, 0xe3, 0xfc, 0xf3, 0xdb, 0x79, 0x78, 0x26,
	0x0b, 0x47, 0x39, 0xca, 0x2c, 0x55, 0x2a, 0x15, 0x7c, 0x95, 0x4b, 0x51, 0x08, 0x72, 0x78, 0x19,
	0x7d, 0x5d, 0x35, 0xa7, 0x8a, 0xfd, 0x0c, 0x60, 0xf8, 0x0e, 0x79, 0x49, 0x1e, 0xc1, 0x58, 0x62,
	0x2c, 0x64, 0x42, 0x83, 0x45, 0xb0, 0x9c, 0x86, 0xd6, 0x23, 0x04, 0x86, 0x3c, 0xca, 0x90, 0xee,
	0x9b, 0x53, 0x63, 0x93, 0x39, 0x1c, 0x28, 0xfc, 0x56, 0x22, 0x8f, 0x91, 0x0e, 0x16, 0xc1, 0x72,
	0x10, 0xd6, 0xbe, 0xd6, 0xa7, 0xb1, 0xe0, 0x74, 0x58, 0xe9, 0xb5, 0x6d, 0xd8, 0xa2, 0x2c, 0x50,
	0xd2, 0x91, 0x65, 0x1b, 0x4f, 0x9f, 0x9f, 0xa7, 0x49, 0x82, 0x9c, 0x8e, 0x0d, 0xc5, 0x7a, 0x9a,
	0x9f, 0x47, 0x12, 0x79, 0xf1, 0x36, 0xa1, 0x13, 0xf3, 0x46, 0xed, 0x93, 0xc7, 0x00, 0x95, 0x7d,
	0x1a, 0x15, 0xe7, 0xf4, 0xc0, 0x3c, 0x75, 0x4e, 0x08, 0x85, 0x49, 0x2c, 0x31, 0x2a, 0x84, 0xa4,
	0x53, 0xf3, 0x70, 0xed, 0xb2, 0xeb, 0x00, 0x66, 0xaf, 0xb4, 0x8d, 0x3a, 0xe1, 0x50, 0x07, 0xac,
	0x8a, 0x5b, 0x90, 0xf7, 0x03, 0x20, 0x6e, 0xda, 0x2a, 0x17, 0x5c, 0x21, 0x3b, 0x86, 0xd9, 0x6b,
	0xbc, 0xc0, 0x9d, 0x8a, 0xa1, 0x11, 0xae, 0xd8, 0x22, 0x74, 0x41, 0x3f, 0xe5, 0xc9, 0x6d, 0x2c,
	0xa8, 0x9b, 0xb6, 0xad, 0xc6, 0x73, 0x38, 0xfa, 0x50, 0xa2, 0xbc, 0x6c, 0xd5, 0x22, 0x8f, 0x64,
	0x94, 0x29, 0x53, 0x8b, 0xbb, 0xa1, 0xf5, 0xd8, 0x19, 0xcc, 0x1c, 0x6d, 0x05, 0xd0, 0x09, 0x27,
	0x51, 0x11, 0x59, 0xa9, 0xb1, 0xc9, 0x31, 0x8c, 0x32, 0xe4, 0xa5, 0xa2, 0xfb, 0x8b, 0xc1, 0xf2,
	0xce, 0xc9, 0xc3, 0x55, 0x6b, 0x7e, 0x57, 0x86, 0x50, 0x69, 0xd8, 0x12, 0xee, 0xbd, 0xc1, 0x62,
	0x97, 0x7e, 0xfe, 0x0a, 0xe0, 0xb0, 0x96, 0xda, 0x9f, 0xbf, 0xf9, 0x7d, 0xbb, 0xaa, 0x17, 0x40,
	0x28, 0x2e, 0xf0, 0x2f, 0xdc, 0xd7, 0x0c, 0x33, 0xb1, 0xce, 0x5b, 0xdb, 0x6e, 0x2c, 0x23, 0xcf,
	0x50, 0x56, 0xa1, 0xb4, 0x87, 0x72, 0x87, 0x00, 0x9b, 0xa1, 0xdc, 0x40, 0x5c, 0xd5, 0x43, 0xf9,
	0x5f, 0x24, 0xe9, 0x86, 0x62, 0x23, 0x24, 0x76, 0x50, 0x9c, 0xf8, 0xd8, 0x7d, 0x3b, 0x10, 0x1b,
	0xc2, 0x97, 0xe6, 0x3e, 0xff, 0x61, 0x1a, 0xec, 0x47, 0x75, 0xc7, 0x5d, 0xe2, 0xbf, 0x29, 0xc3,
	0xc9, 0xf5, 0x18, 0x66, 0xa7, 0xf5, 0xcc, 0x7e, 0x44, 0xf9, 0x3d, 0x8d, 0x91, 0x7c, 0x06, 0x68,
	0xd6, 0x32, 0x61, 0x9d, 0xc9, 0xee, 0x7c, 0xaa, 0xe6, 0xcf, 0xb6, 0x6a, 0x6c, 0xd1, 0xf6, 0x34,
	0xb8, 0x59, 0xd6, 0x3d, 0xe0, 0xce, 0xda, 0xef, 0x01, 0xf7, 0x6c, 0x7b, 0x03, 0x6e, 0xf6, 0x5e,
	0x0f, 0xb8, 0xf3, 0x2d, 0xe8, 0x01, 0xf7, 0x2c, 0xce, 0x3d, 0x72, 0x06, 0xd3, 0x7a, 0x1d, 0x92,
	0xa7, 0x9d, 0x77, 0xda, 0x6b, 0x75, 0xce, 0xb6, 0x49, 0x6a, 0xea, 0x7b, 0x98, 0xd8, 0x1d, 0x47,
	0x9e, 0x74, 0x5e, 0xd8, 0x5c, 0x94, 0xf3, 0x85, 0x5f, 0xe0, 0xa6, 0xdf, 0x8c, 0xac, 0xb7, 0x61,
	0xce, 0x75, 0xf5, 0x36, 0x6c, 0xe3, 0x96, 0x3b, 0x0d, 0xf3, 0x80, 0x3b, 0x2b, 0xc1, 0xdb, 0xb0,
	0x2e, 0xb8, 0x99, 0x3f, 0x6f, 0xc3, 0xb6, 0x83, 0x7b, 0x06, 0xb8, 0x69, 0x98, 0xe1, 0x7a, 0x1a,
	0xe6, 0x62, 0xd9, 0x36, 0x49, 0xab, 0x61, 0x86, 0xd9, 0xdb, 0x30, 0x97, 0xb8, 0xf0, 0x0b, 0xd6,
	0xbc, 0x2f, 0x63, 0xf3, 0x9f, 0xf7, 0xc5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x2d, 0x05,
	0xee, 0x07, 0x0b, 0x00, 0x00,
}
